# Description ------------------------------------------------------------
# Main File Loading Modules and Setup
# Statistical Analysis and Plot Generation

# Load Modules ------------------------------------------------------------
source("partials/setup.R")
source("partials/header.R")
source("partials/map.R")
source("functions/functions.R")

# Results -----------------------------------------------------------------
source("result/01_Beteiligungsrate.R")
source("result/02_Anonym.R")
source("result/03_Submitted.R")
source("result/04_OperationSize.R")
source("result/05_DistMap.R")
source("result/06_Radius.R")
source("result/07_AllYearLosses.R")
source("result/08_Population.R")
source("result/09_Districts.R")
source("result/09_States.R")
source("result/10_Districts.R")
source("result/11_Symptoms.R")
source("result/12_LossDistr.R")
source("result/13_Altitude.R")
source("result/14_OperationSizeLoss.R")
source("result/15_Operational.R")
source("result/15_OperationalNetwork.R")
source("result/16_NewFrames.R")
source("result/17_Crop.R")
source("result/17_CropNetwork.R")
source("result/18_CropMap.R")
source("result/19_VarroaControl.R")
source("result/20_Treatment.R")
source("result/20_TreatmentFreqList.R")
source("result/21_Combination.R")
source("result/22_QueenLossRate.R")
source("result/23_QueenProblems.R")
source("result/24_QueenYoung.R")
source("result/25_CrippledBees.R")
source("result/26_NaturalDisaster.R")
source("result/27_Longitudinal.R")